#!/usr/bin/env bash

# Update package lists
apt-get update -y

# Install nginx
apt-get install nginx -y

ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
service nginx start
