#!/usr/bin/env bash
# Update package lists
sudo apt-get update -y

# Install nginx
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
service nginx restart
