#!/usr/bin/env bash
# Ensures the Nginx configuration is set to listen on port 80
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
kill "$(pgrep 'nginx' | head -1)"
