#!/usr/bin/env bash
# Using awk to group visitors by IP and HTTP status code, count occurrences, and sort the data

awk '{count[$1" "$9]++} END {for (key in count) print count[key], key}' apache-access.log | sort -nr
