#!/usr/bin/env bash
# Define the Nginx configuration file paths
NGINX_CONF="/etc/nginx/nginx.conf"
DEFAULT_SITE_CONF="/etc/nginx/sites-available/default"
sed -i "s/#user www-data/user nginx/" "$NGINX_CONF"
sed -i "s/80/8080/g" "$DEFAULT_SITE_CONF"
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx start
